public enum JobStatuses
{
    UNSENT,
    UNRECEIVED,
    UNFINISHED,
    UNFINISHED_SEND_TO_MASTER,
    ACK_MASTER_RECEIVED,
    UNFINISHED_SEND_TO_SLAVE,
    ACK_SLAVE_RECEIVED,
    FINISHED_SEND_TO_MASTER,
    FINISHED_SEND_TO_CLIENT
}
